In [ ]:
#import libaries
import numpy as np
from numpy import random
import math

In [ ]:
#Aux methods:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

def check_all_matrices(x):
  b = True
  for m in x:
    b = b and is_pos_def(m)
    if not b: return False
  return b

In [ ]:
#generate dataset
n = 50000 #datapoints
d = 3 #dimensions
c = 3 #number of clusters

def create_cov_matrices(cov_list):
  for m in cov_list:
    np.fill_diagonal(m, abs(random.normal(size=(d), scale=spread_of_cluster_centre)))

def generate_dataset(mean_list, cov_list, n):
  x_features = []
  y_labels = random.choice(c, n)
  for i in range(n):
    rand_c = y_labels[i]
    mean = mean_list[rand_c]
    cov = cov_list[rand_c]
    datapoint = np.random.multivariate_normal(mean,cov,(1))
    [datapoint] = datapoint
    x_features.append(datapoint)
  x_features = np.array(x_features)
  return (x_features, y_labels)

spread_of_cluster_centre = math.pi * 3
spread_around_clusters = math.pi * 3
cluster_centres = random.normal(size=(c,d), scale=spread_of_cluster_centre, loc=random.normal(spread_around_clusters))
# print(cluster_centres)

temp = []
for c_i in range(c):
  temp.append(np.zeros((d,d), float))
cov_matrices_list = np.array(temp)
# z = np.zeros((d,d), float)
# cov_matrices_list = np.repeat(z[:, :, np.newaxis], c, axis=2)
# print(cov_matrices_list)
create_cov_matrices(cov_matrices_list)

# print(check_all_matrices(cov_matrices_list))
x_features, y_labels = generate_dataset(cluster_centres, cov_matrices_list, n)

# print(cluster_centres)
# print()
# print(cov_matrices_list)
# print()
# print(x_features)
# print()
# print(y_labels)

#Data preprocessing
x_training_data = x_features
y_training_label = y_labels

In [ ]:
#Data preprocessing
x_training_data = x_features
y_training_label = y_labels

In [ ]:
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_training_data, y_training_label, random_state=42, test_size=0.2)
k_means = KMeans(n_clusters=c, random_state=42, max_iter=100000, tol=1e-6).fit(X_train)
# print(k_means.score(X_test))

print("Misclassification: " + str( (k_means.predict(X_test)!=y_test).sum()) + " out of " + str (len(y_test)))

print(np.sort(cluster_centres, axis=0))
print(np.sort(k_means.cluster_centers_, axis=0))

Misclassification: 270 out of 10000
[[ 5.83832053  4.94949314 -7.50939998]
 [ 8.37182699  9.63217153  6.7041573 ]
 [17.6745843  14.61441055 11.97147719]]
[[ 5.83408253  5.13411771 -7.50158203]
 [ 8.19232523  9.57573555  7.03995519]
 [17.68470834 15.2256476  11.99788309]]


In [ ]:
#GMM
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_training_data, y_training_label, random_state=42, test_size=0.2)
gm = GaussianMixture(n_components=c, covariance_type = "full", tol=1e-6, max_iter=10000, random_state=42, warm_start=True).fit(X_train)

print("Misclassification: " + str( (gm.predict(X_test)!=y_test).sum()) + " out of " + str (len(y_test)))
print("Score: " + str(gm.score(X_test)))


Misclassification: 9989 out of 10000
Score: -7.9973906022864885


In [ ]:
from sklearn.cluster import AgglomerativeClustering
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_training_data, y_training_label, random_state=42, test_size=0.3)
aff_prop_clustering = AgglomerativeClustering(n_clusters=c).fit(X_train)
print("Misclassification: " + str( (aff_prop_clustering.fit_predict(X_test)!=y_test).sum()) + " out of " + str (len(y_test)))

Misclassification: 14988 out of 15000


In [ ]:
from sklearn.cluster import MeanShift

X_train, X_test, y_train, y_test = train_test_split(x_training_data, y_training_label, random_state=42, test_size=0.3)
mean_shift_cluster = MeanShift(bandwidth=2).fit(X_train)
print("Misclassification: " + str( (mean_shift_cluster.predict(X_test)!=y_test).sum()) + " out of " + str (len(y_test)))

In [ ]:
from sklearn.cluster import AffinityPropagation

X_train, X_test, y_train, y_test = train_test_split(x_training_data, y_training_label, random_state=42, test_size=0.3)
aff_prop_clustering = AffinityPropagation(random_state=42, max_iter=20000).fit(X_train)
print("Misclassification: " + str( (aff_prop_clustering.predict(X_test)!=y_test).sum()) + " out of " + str (len(y_test)))